### ISSUE TITLE
Build #43 - Youtube broken

### ISSUE THREAD

**Issue by snuffy22** [ayufan-pine64/device-softwinner#4]
When trying to use the YouTube app you select a video, it will then start playing at a low res.

Soon as it jumps to HD quality, you have a nice still image with sound only.

**Comment by snuffy22** [comment]
My model is Pine 64 with the 2GB RAM + 16GB SD card

**Comment by mikey0000** [comment]
Yup can confirm issue with mine as well. [no issue on 47]

**Comment by ayufan** [comment]
The next build will have that fixed: https://github.com/ayufan-pine64/frameworks-av/commit/db7c7ff0a02699d89b49673dd97d8cad8b79458d
