### ISSUE TITLE
Build #43 - Netflix Broken

### ISSUE THREAD

**Issue by snuffy22** [ayufan-pine64/device-softwinner#5]
Unsure if this is just because its Android v7.0..

But the browsing of Netflix app works fine. The playback is incorrect.

First, until you hit the <-> button on bottom right of app you get no sound.

Second, it seems to be 'missing' part of the video, like my screen is 720 but video is 1080.

Pine is running in 1080p mode and icon size suggests it and TV input says the same 1080 @ 60hz

**Comment by ayufan** [comment]
Try this build. It should be more compatible with Netflix: https://github.com/ayufan-pine64/android-6.0/releases
