### ISSUE TITLE
AndroidKernel.mk does not build mali.ko module

### ISSUE THREAD

**Issue by secuflag** [ayufan-pine64/device-softwinner#6]
As above, I think there is something to add from the file _linux/kernel-tulip/modules/gpu/Makefile_

**Comment by ayufan** [comment]
Interesting :) Probably, because mali module is vendored

**Comment by ayufan** [comment]
Fix https://github.com/ayufan-pine64/device-softwinner/commit/ee5fecc80e38ec8675ff20ec381c09ec2a76a25b

**Comment by secuflag** [comment]
Thank you :+1:
