### ISSUE TITLE
#build 45 audioflinger crashes

### ISSUE THREAD

**Issue by mikey0000** [ayufan-pine64/device-softwinner#9]
cannot open pcm_out driver: cannot open device '/dev/snd/pcmC0D0p': No such file or directory

**Comment by ayufan** [comment]
Interesting. My manual build works fine...

Could you try the old one?

**Comment by mikey0000** [comment]
Unfortunately I need the pine64 working for my kids and wife lol so I'll do my best. Doing another burn now.

[EDIT] false alarm bad burn.

**Comment by mikey0000** [comment]
do you have sound working?
